import Link from 'next/link'
import { ArrowRight, BarChart3, Building2, Check, ChevronDown, CircleDollarSign, FileText, MessageCircle, ShieldCheck, Sparkles, Wrench } from 'lucide-react'
import { Button } from '@/components/ui/button'
import RoiCalculator from '@/components/marketing/RoiCalculator'

const features = [
  { icon: CircleDollarSign, title: 'Collect rent with confidence', text: 'Payfast-ready collections, automatic matching and a live view of every rand due, paid and outstanding.' },
  { icon: MessageCircle, title: 'Follow up without friction', text: 'Send timely WhatsApp reminders and updates while keeping consent, delivery status and the full trail in one place.' },
  { icon: Wrench, title: 'Resolve maintenance faster', text: 'Turn tenant requests into clear jobs, quotes and approvals. Keep owners, tenants and contractors aligned.' },
  { icon: BarChart3, title: 'Know your real performance', text: 'See occupancy, arrears, yield and cash flow without stitching together spreadsheets and bank exports.' },
  { icon: FileText, title: 'Statements that reconcile', text: 'Give owners clean, accurate statements with VAT-aware reporting and fewer end-of-month surprises.' },
  { icon: ShieldCheck, title: 'Automation you can trust', text: 'Permissioned workflows, audit logs and approval gates keep your data and decisions in your hands.' },
]

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-[#fbfcfb] text-slate-900">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><Link href="/" className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#193b37] text-white"><Building2 size={18} /></span><span className="text-lg font-bold tracking-tight">Lease Sentinel</span></Link><div className="hidden items-center gap-8 text-sm font-medium text-slate-500 md:flex"><Link href="#how-it-works" className="hover:text-slate-900">How it works</Link><Link href="#features" className="hover:text-slate-900">Features</Link><Link href="#roi" className="hover:text-slate-900">Calculate your ROI</Link><Link href="/pricing" className="hover:text-slate-900">Pricing</Link></div><div className="flex items-center gap-3"><Link href="/login" className="hidden text-sm font-semibold text-slate-600 sm:block">Sign in</Link><Link href="/demo"><Button className="rounded-lg bg-[#193b37] px-4 hover:bg-[#27564f]">See the demo <ArrowRight size={15} /></Button></Link></div></nav>

    <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-14 md:px-8 md:pb-28 md:pt-24"><div className="absolute -right-32 -top-24 h-[32rem] w-[32rem] rounded-full bg-[#dff0e9] blur-3xl" /><div className="relative grid items-center gap-14 lg:grid-cols-[1.02fr_.98fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#cfe4dd] bg-white px-3 py-1.5 text-xs font-bold text-[#287366]"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />Built for South African property teams</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.04] tracking-[-.05em] md:text-7xl">Collect every rand.<br /><span className="text-[#287366]">Chase no one.</span></h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-slate-500">Lease Sentinel brings rent collection, arrears, maintenance and owner reporting into one calm workspace—so your portfolio grows without the admin growing with it.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/demo"><Button size="lg" className="h-12 rounded-xl bg-[#193b37] px-5 hover:bg-[#27564f]">Start with a guided demo <ArrowRight size={17} /></Button></Link><Link href="#roi" className="text-sm font-bold text-[#287366] hover:underline">Calculate your upside</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs font-medium text-slate-500"><span className="flex items-center gap-1.5"><Check size={14} className="text-emerald-600" />No card required</span><span className="flex items-center gap-1.5"><Check size={14} className="text-emerald-600" />POPIA-minded</span><span className="flex items-center gap-1.5"><Check size={14} className="text-emerald-600" />Payfast-ready</span></div></div><DashboardMock /></div></section>

    <section className="border-y border-slate-200 bg-white py-5"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-10 gap-y-3 px-5 text-xs font-bold uppercase tracking-[.14em] text-slate-400 md:justify-between md:px-8"><span>Payfast</span><span>WhatsApp</span><span>Xero</span><span>Sage</span><span>Bank CSV</span><span>Built for ZAR & VAT</span></div></section>

    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#287366]">A simpler operating rhythm</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">The work gets done.<br />You stay in control.</h2><p className="mt-5 max-w-md leading-relaxed text-slate-500">Replace scattered tools and manual follow-ups with a system that keeps every important detail moving.</p></div><div className="grid gap-4 sm:grid-cols-3"><Step number="01" title="Connect" text="Import your rent roll and connect collections, messages and accounting." /><Step number="02" title="Automate" text="Set rules for reminders, reconciliations, maintenance and reporting." /><Step number="03" title="Improve" text="See what needs attention and make better decisions from one live view." /></div></div></section>

    <section id="features" className="bg-white py-20 md:py-28"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#287366]">One source of truth</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">Everything your portfolio needs.<br />Nothing it doesn&apos;t.</h2></div><Link href="/demo" className="flex items-center gap-1 text-sm font-bold text-[#287366]">Tour the workspace <ArrowRight size={15} /></Link></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(feature => <Feature key={feature.title} {...feature} />)}</div></div></section>

    <section id="roi" className="mx-auto max-w-7xl scroll-mt-10 px-5 py-20 md:px-8 md:py-28"><div className="mx-auto mb-10 max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#287366]">Make the business case</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">Your admin has a cost.<br />Your time has a value.</h2><p className="mt-5 text-slate-500">Use the calculator to see the opportunity in your own portfolio.</p></div><RoiCalculator /></section>

    <section className="bg-[#193b37] py-20 text-white md:py-24"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 md:grid-cols-[1fr_auto] md:px-8"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#f4c95d]">Ready when you are</p><h2 className="mt-4 max-w-2xl text-3xl font-bold tracking-tight md:text-5xl">Stop managing around the gaps.</h2><p className="mt-5 max-w-xl leading-relaxed text-emerald-100">See how Lease Sentinel can give your team back the hours spent chasing payments, people and paperwork.</p></div><Link href="/demo"><Button size="lg" className="h-13 rounded-xl bg-white px-6 text-[#193b37] hover:bg-[#f4c95d]">Book a guided demo <ArrowRight size={17} /></Button></Link></div></section>

    <section className="mx-auto max-w-3xl px-5 py-20 md:px-8"><h2 className="text-center text-3xl font-bold tracking-tight">Questions, answered.</h2><div className="mt-8 divide-y divide-slate-200 border-y border-slate-200">{[['Will this replace my current payment provider?', 'No. Sentinel connects to the tools you already use, including Payfast, while giving you one reliable reconciliation layer.'], ['How quickly can we get started?', 'Most teams can import a rent roll and see their first useful dashboard in a day. We will guide you through the rest.'], ['Is my data safe?', 'Access controls, audit trails, encryption and approval gates are built into the product. You decide who can see and do what.'], ['Is it only for residential rentals?', 'No. Sentinel is designed for mixed portfolios, including commercial and industrial property.']].map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between font-bold">{question}<ChevronDown size={18} className="transition group-open:rotate-180" /></summary><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-500">{answer}</p></details>)}</div></section>

    <footer className="border-t border-slate-200"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-5 py-8 text-sm text-slate-400 sm:flex-row md:px-8"><span className="font-bold text-slate-700">Lease Sentinel</span><span>Property operations, made clearer. © 2026</span></div></footer>
  </main>
}

function DashboardMock() { return <div className="relative"><div className="rounded-3xl border border-slate-200 bg-white p-3 shadow-[0_24px_80px_-24px_rgba(25,59,55,.35)]"><div className="rounded-2xl bg-[#f7f8fa] p-5 md:p-7"><div className="mb-7 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider text-slate-400">Portfolio overview</p><p className="mt-1 text-xl font-bold">Good morning, Alex 👋</p></div><div className="h-9 w-9 rounded-full bg-[#d9e9e4]" /></div><div className="grid grid-cols-2 gap-3"><MiniStat label="Collected this month" value="R 1.28m" trend="+4.8%" /><MiniStat label="Arrears" value="R 42.6k" trend="-18.2%" /></div><div className="mt-3 rounded-xl border border-slate-200 bg-white p-4"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-bold">Collections this month</span><span className="text-[10px] font-bold text-emerald-600">94.2% collected</span></div><div className="flex h-24 items-end justify-around gap-2">{[42,58,50,76,65,88,73,92].map((height, index) => <div key={index} className="flex h-full flex-1 items-end gap-1"><i className="w-1/2 rounded-t bg-[#b8d8ce]" style={{ height: `${height * .66}%` }} /><i className="w-1/2 rounded-t bg-[#193b37]" style={{ height: `${height}%` }} /></div>)}</div></div><div className="mt-3 flex items-center gap-3 rounded-xl border border-[#cfe4dd] bg-[#eef7f3] p-3"><Sparkles size={16} className="text-[#287366]" /><p className="text-[11px] font-medium leading-relaxed text-slate-600">3 payments matched automatically today.</p></div></div></div><div className="absolute -bottom-5 -left-5 hidden items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-lg sm:flex"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-orange-50 text-orange-600"><Wrench size={16} /></span><div><p className="text-xs font-bold">4 maintenance items</p><p className="text-[10px] text-slate-400">1 needs your attention</p></div></div></div> }
function MiniStat({ label, value, trend }: { label: string; value: string; trend: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-[10px] text-slate-400">{label}</p><p className="mt-1 text-lg font-bold">{value}</p><p className="mt-1 text-[10px] font-bold text-emerald-600">↗ {trend}</p></div> }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><span className="text-xs font-bold text-[#287366]">{number}</span><h3 className="mt-10 font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-500">{text}</p></div> }
function Feature({ icon: Icon, title, text }: { icon: React.ElementType; title: string; text: string }) { return <div className="rounded-2xl border border-slate-200 bg-[#fbfcfb] p-6 transition hover:-translate-y-0.5 hover:border-[#b8d8ce] hover:shadow-lg"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eef7f3] text-[#287366]"><Icon size={19} /></span><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-500">{text}</p></div> }
