'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, CalendarDays, Plus, Repeat2, Wrench } from 'lucide-react'
import { Button } from '@/components/ui/button'

type Schedule = { id: string; title: string; description?: string; next_due_date: string; frequency_months: number; properties?: { name?: string } }
export default function MaintenanceCalendar() {
  const [schedules, setSchedules] = useState<Schedule[]>([])
  const [message, setMessage] = useState('')
  useEffect(() => { fetch('/api/maintenance?status=all').then(response => response.json()).then(data => setSchedules(data.schedules || [])).catch(() => setMessage('Could not load schedules.')) }, [])
  return <main className="min-h-screen bg-[#f7f8fa] text-slate-900"><header className="flex h-[72px] items-center justify-between border-b border-slate-200 bg-white px-5 md:px-8"><div className="flex items-center gap-3"><Link href="/dashboard/maintenance" className="rounded-lg p-2 text-slate-500"><ArrowLeft size={18} /></Link><div><p className="text-xs text-slate-400">Maintenance / Preventative care</p><h1 className="text-lg font-bold">Maintenance calendar</h1></div></div><Button className="gap-2 rounded-xl bg-[#193b37]"><Plus size={16} /> Add schedule</Button></header><div className="mx-auto max-w-5xl px-5 py-8 md:px-8"><div className="rounded-2xl border border-[#cfe4dd] bg-[#eef7f3] p-6"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#287366]"><Repeat2 size={16} /> Preventative maintenance</div><h2 className="mt-3 text-3xl font-bold">Prevent problems before they become emergencies.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-600">Keep HVAC servicing, inspections, pest control and safety checks visible across every property.</p></div><div className="mt-7 grid gap-3">{schedules.map(schedule => <div key={schedule.id} className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eef7f3] text-[#287366]"><Wrench size={19} /></span><div className="min-w-0 flex-1"><h3 className="font-bold">{schedule.title}</h3><p className="mt-1 text-xs text-slate-500">{schedule.properties?.name || 'Property'} · Every {schedule.frequency_months} month{schedule.frequency_months === 1 ? '' : 's'}</p>{schedule.description && <p className="mt-2 text-xs text-slate-400">{schedule.description}</p>}</div><div className="text-right"><span className="flex items-center gap-1 text-xs font-bold text-[#287366]"><CalendarDays size={14} /> {new Date(schedule.next_due_date).toLocaleDateString('en-ZA', { day: 'numeric', month: 'short', year: 'numeric' })}</span><span className="mt-1 block text-[10px] text-slate-400">Next due</span></div></div>)}{!schedules.length && <div className="rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center"><CalendarDays className="mx-auto text-slate-300" size={28} /><p className="mt-3 text-sm font-semibold">No preventative schedules yet</p><p className="mt-1 text-xs text-slate-400">Add regular inspections and service plans to get ahead of maintenance.</p></div>}</div></div>{message && <p className="fixed bottom-5 right-5 rounded-lg bg-[#193b37] px-4 py-3 text-white">{message}</p>}</main>
}
