'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, CircleDollarSign, Wrench } from 'lucide-react'
import { Button } from '@/components/ui/button'

const questions = [{ label: 'How many units do you manage?', options: ['1–10', '11–75', '76–500', '500+'] }, { label: 'What is your biggest challenge?', options: ['Rent collection', 'Maintenance', 'Reporting', 'Too many tools'] }, { label: 'What do you manage?', options: ['Residential', 'Commercial', 'Industrial', 'Mixed portfolio'] }, { label: 'How do tenants contact you?', options: ['WhatsApp', 'Email', 'Phone', 'A mix of everything'] }]
export default function HealthCheck() { const [step, setStep] = useState(0); const [answers, setAnswers] = useState<string[]>([]); const done = step === questions.length; const result = answers[1] === 'Maintenance' ? { title: 'Your biggest win is a maintenance command centre.', text: 'You are likely losing time to unstructured requests, quote chasing and tenant follow-ups.', icon: Wrench } : { title: 'Your biggest win is financial control.', text: 'A live rent roll, arrears workflow and owner reporting can give you back control of your portfolio.', icon: CircleDollarSign }; return <main className="min-h-screen bg-[#fbfcfb] text-slate-900"><nav className="mx-auto flex max-w-4xl items-center gap-4 px-5 py-6"><Link href="/" className="rounded-lg p-2 text-slate-500"><ArrowLeft size={18} /></Link><span className="text-lg font-bold">Portfolio health check</span></nav><section className="mx-auto max-w-2xl px-5 pb-20 pt-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#287366]">A 60-second assessment</p>{!done ? <><div className="mt-6 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#193b37] transition-all" style={{ width: `${(step / questions.length) * 100}%` }} /></div><p className="mt-6 text-xs text-slate-400">Question {step + 1} of {questions.length}</p><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-5xl">{questions[step].label}</h1><div className="mt-8 grid gap-3">{questions[step].options.map(option => <button key={option} onClick={() => { setAnswers(current => [...current, option]); setStep(current => current + 1) }} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 text-left font-semibold transition hover:border-[#287366] hover:bg-[#eef7f3]">{option}<ArrowRight size={17} className="text-slate-300" /></button>)}</div></> : <div className="rounded-3xl bg-[#193b37] p-7 text-white md:p-10"><CheckCircle2 className="text-[#f4c95d]" size={26} /><h1 className="mt-6 text-3xl font-bold leading-tight">{result.title}</h1><p className="mt-4 text-sm leading-relaxed text-emerald-100">{result.text}</p><div className="mt-7 rounded-2xl bg-white/10 p-4"><result.icon className="text-[#f4c95d]" size={21} /><p className="mt-3 text-sm font-semibold">Recommended starting point</p><p className="mt-1 text-xs text-emerald-100">Import your portfolio, connect your collection workflow and activate the daily attention view.</p></div><Link href="/login"><Button className="mt-7 gap-2 rounded-xl bg-white text-[#193b37] hover:bg-emerald-50">Build my workspace <ArrowRight size={16} /></Button></Link></div>}</section></main> }
